---
- name: Find Empty Directories
  hosts: your_target_host
  gather_facts: no  # Disable gathering facts to speed up the playbook

  tasks:
    - name: Find Empty Directories
      find:
        paths: /path/to/search  # Replace with the directory you want to search
        recurse: yes
        file_type: directory
        empty: yes
      register: empty_dirs

    - name: Display Empty Directories
      debug:
        var: empty_dirs.files
