---
- name: Find All Files in Directory Tree (Ignoring Specific Directories)
  hosts: your_target_host
  gather_facts: no  # Disable gathering facts to speed up the playbook

  tasks:
    - name: Find All Files
      find:
        paths: /path/to/search  # Replace with the directory you want to search
        recurse: yes
        file_type: file
        exclude_paths:
          - /path/to/search/dir_to_ignore1
          - /path/to/search/dir_to_ignore2
      register: found_files

    - name: Display Found Files
      debug:
        var: found_files.files
